# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(793, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setIconSize(QtCore.QSize(60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget.setObjectName("listWidget")

        self.horizontalLayout.addWidget(self.listWidget, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.addImgButton = QtWidgets.QPushButton(self.centralwidget)
        self.addImgButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/addimage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addImgButton.setIcon(icon)
        self.addImgButton.setIconSize(QtCore.QSize(25, 25))
        self.addImgButton.setFlat(True)
        self.addImgButton.setObjectName("addImgButton")

        self.horizontalLayout_3.addWidget(self.addImgButton)

        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon1)
        self.deleteButton.setIconSize(QtCore.QSize(25, 25))
        self.deleteButton.setFlat(True)
        self.deleteButton.setObjectName("deleteButton")

        self.horizontalLayout_3.addWidget(self.deleteButton)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.leftRotButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftRotButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/leftrotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftRotButton.setIcon(icon2)
        self.leftRotButton.setIconSize(QtCore.QSize(25, 25))
        self.leftRotButton.setFlat(True)
        self.leftRotButton.setObjectName("leftRotButton")

        self.horizontalLayout_4.addWidget(self.leftRotButton, 0, QtCore.Qt.AlignLeft)

        self.rightRotButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightRotButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/rightrotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightRotButton.setIcon(icon3)
        self.rightRotButton.setIconSize(QtCore.QSize(25, 25))
        self.rightRotButton.setFlat(True)
        self.rightRotButton.setObjectName("rightRotButton")

        self.horizontalLayout_4.addWidget(self.rightRotButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)

        self.label.setMinimumSize(QtCore.QSize(256, 0))
        self.label.setMaximumSize(QtCore.QSize(512, 512))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setBaseSize(QtCore.QSize(0, 0))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(False)
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")

        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon4)
        self.leftButton.setIconSize(QtCore.QSize(25, 25))
        self.leftButton.setFlat(True)
        self.leftButton.setObjectName("leftButton")

        self.horizontalLayout_5.addWidget(self.leftButton, 0, QtCore.Qt.AlignLeft)

        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon5)
        self.rightButton.setIconSize(QtCore.QSize(25, 25))
        self.rightButton.setFlat(True)
        self.rightButton.setObjectName("rightButton")

        self.horizontalLayout_5.addWidget(self.rightButton, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(650, 0))
        self.tableView.setMaximumSize(QtCore.QSize(710, 16777215))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)

        self.verticalLayout_2.addWidget(self.tableView)

        self.mapButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/map.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mapButton.setIcon(icon6)
        self.mapButton.setIconSize(QtCore.QSize(25, 25))
        self.mapButton.setObjectName("mapButton")
        self.mapButton.setFont(QtGui.QFont('', 12))

        self.verticalLayout_2.addWidget(self.mapButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Exif Viewer"))
        self.label.setText(_translate("MainWindow", "Double Click to View Exif"))
        self.mapButton.setText(_translate("MainWindow", "Open Map"))
